In [18]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from game_map import GameMap, Run 

In [14]:
m = GameMap(5)
run = Run(m, [1,1])
m.print()

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [15]:
for direction in 'DR U L D'.split():
    if not run.move(direction):
        print('error')
    m.print()
    print()
    

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  3.  0.]
 [ 0.  1.  0.  3.  0.]
 [ 0.  0.  2.  3.  0.]
 [ 0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 4.  4.  4.  3.  0.]
 [ 0.  1.  0.  3.  0.]
 [ 0.  0.  2.  3.  0.]
 [ 0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 4.  4.  4.  3.  0.]
 [ 5.  1.  0.  3.  0.]
 [ 5.  0.  2.  3.  0.]
 [ 5.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.]]

