In [1]:
import numpy as np

In [2]:
from state import State

In [3]:
s0 = State([1, 1], )
s0.grid.print()

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
def try_run(starting_coords):
    s0 = State(starting_coords)
    out, state = recursive_run(s0)
    return out, state
    

In [9]:
def recursive_run(state):
    
    if state is not False:
        print(state.path)
        state.grid.print()
        print()

    if state.grid.solved(): 
        print('~wtf pass')
        return True, state

    else: 
        for direction in "U L D R UR UL DR DL".split():
            if state.is_move_possible(direction) is False:
                continue
            else: 
                new_state = state.apply_move(direction)
                out, s = recursive_run(new_state)
                if out is False: 
                    continue
                else: 
                    return True, s
    
    return False, state

In [7]:
for i in range(5):
    for j in range(5):
        out, s = try_run([i, j])
        
        print(out)
        if out is not False:
            s.grid.print()

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [12]:
out, s = try_run([1, 1])


[]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

['D']
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]

['D', 'R']
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'U']
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4.]
 [0. 2. 0. 0. 4.]
 [0. 2. 0. 0. 4.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'U', 'DL']
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4.]
 [0. 2. 0. 5. 4.]
 [0. 2. 5. 0. 4.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'U', 'DL', 'U']
[[0. 0. 6. 0. 0.]
 [0. 1. 6. 0. 4.]
 [0. 2. 6. 5. 4.]
 [0. 2. 5. 0. 4.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'UL']
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 4. 0. 0.]
 [0. 2. 0. 4. 0.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'UL', 'UR']
[[0. 0. 0. 0. 5.]
 [0. 1. 0. 5. 0.]
 [0. 2. 4. 0. 0.]
 [0. 2. 0. 4. 0.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'UL', 'UR', 'L']
[[0. 6. 6. 6. 5.]
 [0. 1. 0. 5. 0.]
 [0. 2. 4. 0. 0.]
 [0. 2. 0. 4. 0.]
 [0. 2. 3. 3. 3.]]

['D', 'R', 'UL', 'U