In [1]:
import numpy as np

In [2]:
from state import State
import utilities

In [3]:
s0 = State([1, 1], )
s0.grid.print()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
solutions = utilities.solve_for_solutions()

Solving for initial coords: (0, 0)...done
Solving for initial coords: (0, 1)...done
Solving for initial coords: (0, 2)...done
Solving for initial coords: (0, 3)...done
Solving for initial coords: (0, 4)...done
Solving for initial coords: (1, 0)...done
Solving for initial coords: (1, 1)...done
Solving for initial coords: (1, 2)...done
Solving for initial coords: (1, 3)...done
Solving for initial coords: (1, 4)...done
Solving for initial coords: (2, 0)...done
Solving for initial coords: (2, 1)...done
Solving for initial coords: (2, 2)...done
Solving for initial coords: (2, 3)...done
Solving for initial coords: (2, 4)...done
Solving for initial coords: (3, 0)...done
Solving for initial coords: (3, 1)...done
Solving for initial coords: (3, 2)...done
Solving for initial coords: (3, 3)...done
Solving for initial coords: (3, 4)...done
Solving for initial coords: (4, 0)...done
Solving for initial coords: (4, 1)...done
Solving for initial coords: (4, 2)...done
Solving for initial coords: (4, 3)

In [5]:
total_grid = np.zeros([5, 5, 2])

for s0, ans, count in solutions: 
#     print(s0, len(ans))
    total_grid[s0[0], s0[1]] = (len(ans), count)

In [6]:
sols_grid = total_grid[:,:,0]
count_grid = total_grid[:,:,1]

In [7]:
print('number of solutions per starting square')
sols_grid

number of solutions per starting square


array([[552., 548., 552., 548., 552.],
       [548., 412., 400., 412., 548.],
       [552., 400., 352., 400., 552.],
       [548., 412., 400., 412., 548.],
       [552., 548., 552., 548., 552.]])

In [8]:
print('total number of feasible paths per starting square')
count_grid

total number of feasible paths per starting square


array([[103841.,  98517.,  98404.,  98517., 103841.],
       [ 98517.,  95490.,  88884.,  95490.,  98517.],
       [ 98404.,  88884.,  70269.,  88884.,  98404.],
       [ 98517.,  95490.,  88884.,  95490.,  98517.],
       [103841.,  98517.,  98404.,  98517., 103841.]])

In [9]:
ratio_grid = (sols_grid/ count_grid)
print('ratio of solution paths to total feasible paths')
ratio_grid

ratio of solution paths to total feasible paths


array([[0.00531582, 0.00556249, 0.00560953, 0.00556249, 0.00531582],
       [0.00556249, 0.00431459, 0.00450025, 0.00431459, 0.00556249],
       [0.00560953, 0.00450025, 0.00500932, 0.00450025, 0.00560953],
       [0.00556249, 0.00431459, 0.00450025, 0.00431459, 0.00556249],
       [0.00531582, 0.00556249, 0.00560953, 0.00556249, 0.00531582]])

In [10]:
import seaborn as sns 
fig = sns.heatmap(sols_grid, annot=True)
fig.figure.axes[0].set_title('solutions per starting square');

In [11]:
import seaborn as sns 
fig = sns.heatmap(ratio_grid, annot=True)
fig.figure.axes[0].set_title('ratio of solutions/total paths per starting square');

In [12]:
fig = utilities.plot_solved_grid(solutions[0][1][1].grid.grid);

In [13]:
fig, path = utilities.plot_some_random_solution_idc_which_one(solutions);
print(path)

['UR', 'D', 'UL', 'R', 'DL', 'UL', 'UR', 'D', 'UL', 'D', 'UR', 'UL', 'R', 'D', 'UL', 'R', 'D', 'L', 'UR', 'UL', 'R', 'D', 'UL', 'DL']


In [14]:
sol = solutions[1]

avg_grid = np.zeros([5,5])

# for sol in solutions: 
for state in sol[1]:
    avg_grid += state.grid.grid
avg_grid = avg_grid / len(sol[1])
avg_grid

array([[15.20985401,  1.        , 13.59124088, 14.98722628,  8.83211679],
       [12.42883212, 15.16970803, 15.47262774, 10.73540146, 14.70437956],
       [14.13686131, 13.67518248, 12.7189781 , 13.07481752, 14.37773723],
       [15.37226277,  9.58941606, 13.18430657, 15.22080292, 11.83576642],
       [13.12591241, 14.60948905, 15.19708029, 12.36678832, 14.38321168]])