In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from game_map import GameMap
from run import Run 

In [3]:
m = GameMap(5)
run = Run(m, [1,1])
m.print()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# for i in range(5):
#     for j in range(5): 
m.try_run([1, 1])
m.reset()

D
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]

R
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 2. 3. 3. 3.]]

U
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4.]
 [0. 2. 0. 0. 4.]
 [0. 2. 0. 0. 4.]
 [0. 2. 3. 3. 3.]]

DL
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4.]
 [0. 2. 0. 5. 4.]
 [0. 2. 5. 0. 4.]
 [0. 2. 3. 3. 3.]]

U
[[0. 0. 6. 0. 0.]
 [0. 1. 6. 0. 4.]
 [0. 2. 6. 5. 4.]
 [0. 2. 5. 0. 4.]
 [0. 2. 3. 3. 3.]]

all failed.  path:  D R U DL U
 D R U DL U


In [7]:
if run.move('U') is not False: 
    print(run)
else: 
    print("n", run)

n <run.Run object at 0x0000021DE04281D0>


In [8]:
for direction in 'DR U L D'.split():
    if not run.move(direction):
        print('error')
    m.print()
    print()
    

error
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

error
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

error
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

error
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [9]:
" ".join(['U L D', 'D'])

'U L D D'

In [10]:
run.move('DR')

False