In [1]:
import numpy as np

In [2]:
from state import State

In [3]:
s0 = State([1, 1], )
s0.grid.print()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
s1 = s0.apply_move('D')
s1.grid.print()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [5]:
s2 = s1.apply_move('UR')
s2.grid.print()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [8]:
def try_run(starting_coords):
    s0 = State(starting_coords)
    out, state = recursive_run(s0)
    return out, state
    

In [13]:
def recursive_run(state):
    
#     if state is not False:
#         print(state.path)
#         state.grid.print()
#         print()

    if state.grid.solved(): 
        print('\n\n~passed')
        return True, state

    else: 
        for direction in "U L D R UR UL DR DL".split():
            if state.is_move_possible(direction) is False:
                continue
            else: 
                new_state = state.apply_move(direction)
                out, s = recursive_run(new_state)
                if out is False: 
                    continue
                else: 
                    return True, s
    
    return False, state

In [17]:
for i in range(5):
    for j in range(5):
        out, s = try_run([i, j])
        
        if out is not False:
            print('Starting coords: ({}, {})'.format(i, j))
            print(s.path)
            s.grid.print()



~passed
Starting coords: (0, 0)
['D', 'R', 'U', 'DL', 'R', 'UL', 'D', 'UR', 'L', 'D', 'R', 'UL', 'UR', 'L', 'DR', 'L', 'DR', 'U', 'DR', 'L', 'UR', 'L', 'D', 'R']
[[ 1. 15.  7.  4. 14.]
 [23. 10. 19. 22.  9.]
 [17.  5. 13. 16.  6.]
 [ 2. 21.  8.  3. 20.]
 [24. 11. 18. 25. 12.]]


~passed
Starting coords: (0, 1)
['D', 'R', 'U', 'DL', 'UL', 'D', 'UR', 'D', 'UR', 'L', 'UR', 'D', 'UL', 'R', 'D', 'L', 'UR', 'L', 'UR', 'D', 'UL', 'D', 'R', 'U']
[[ 6.  1. 20. 12.  4.]
 [22. 14.  8. 25. 15.]
 [19. 11.  5. 18. 10.]
 [ 7.  2. 21. 13.  3.]
 [23. 17.  9. 24. 16.]]


~passed
Starting coords: (0, 2)
['D', 'UR', 'L', 'D', 'R', 'UL', 'UR', 'L', 'DR', 'L', 'DR', 'UR', 'L', 'DR', 'L', 'U', 'R', 'DL', 'R', 'UL', 'DL', 'U', 'R', 'D']
[[23.  9.  1. 24.  8.]
 [17.  4. 21. 18.  3.]
 [11. 14.  7. 10. 13.]
 [22. 19.  2. 25. 20.]
 [16.  5. 12. 15.  6.]]


~passed
Starting coords: (0, 3)
['L', 'D', 'R', 'UL', 'D', 'R', 'U', 'DL', 'U', 'DR', 'L', 'DR', 'U', 'L', 'D', 'UR', 'UR', 'L', 'D', 'R', 'UL', 'D', 'UL', '